# This is free and unencumbered software released into the public domain.

name: deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Deploy
        uses: devcontainers/ci@v0.3
        with:
          env: |
            CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT }}
            CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_TOKEN }}
          push: never
          runCmd: |
            npm ci
            npm run deploy
